### PR TITLE
T11740

### PR DESCRIPTION
**Pull request by carlocaione**
https://phabricator.endlessm.com/T11740

### CODE REVIEW

**Comment by dsd** [comment]
I didn't realise that we were already shipping vbox drivers. Can we just stick with the version shipped with ubuntu (5.0.16)? Or if we update to the latest xenial 4.4 kernel we'll get version 5.0.18.

**Comment by carlocaione** [comment]
We can, but we would need to submit again the guests package in T11739 to match the version shipped in ubuntu.

**Comment by dsd** [comment]
That sounds like a good move to keep this from being a maintenance headache. But are you sure they have to be in sync? It's perhaps a broken development version, but Ubuntu Yakkety appears to ship 5.0.18 kernel + 5.0.20 userspace right now.

**Comment by carlocaione** [comment]
well, not sure, I'm just assuming here and I'm scared we can diverge too much soon. I can try with 5.0.16 kernel + 5.0.20 userspace

**Pull request closed without merging**
