### PR TITLE
Fix order of remapped nvme devices.

### PR DESCRIPTION
**Pull request by mithrandir42**
Nvme devices are being ordered the opposite way in rst mode than in ahci
mode. I.e., with three drives, nvme0n1(in ahci mode) becomes nvme2n1 in
rst mode. For non initrd users this means grub cannot find the root
partition when switching between ahci and rst in bios.

### CODE REVIEW

**Comment by jprvita** [comment]
test this please

**Comment by jprvita** [comment]
@mithrandir42 The commit message text looks good now, thanks!

I just realized the author is a `@users.noreply.github.com` address -- can you share an email address to be used as the commit author and signed-off-by? Then I can manually update it on the commit message before merging (or, if you prefer to update the commit yourself with a proper author email and signed-off, that works too). Sorry I have missed this on the previous review.

In any case, we still need to wait @dsd for a proper code review + approval, but then I can do the manual merge work.

**Comment by mithrandir42** [comment]
Sure we have to wait. Just wanted to prepare the PR, well and broke it... Seems to happen when wants so save time by not cloning the full history...
Did the signed-off-by entry myself for learning. Hoping I did it right. Didn't expect this to get that complicated ;)

**Comment by jprvita** [comment]
@mithrandir42 Thanks! The commit authorship and signed-off-by look good now!

**Comment by dsd** [comment]
The kernel doesn't generally make any promises around persistent device node naming. If the names are already stable in some way, I believe that is more viewed as luck, rather than something you can rely on. And e.g. if you were using USB disks instead I expect you would be considerably less lucky. This situation really calls for an initramfs.

Anyway, if there is some indication in the spec that the disks are somehow listed in reverse then I would accept this anyway - would you mind checking that? The info I used when working on this is in
https://www.intel.com/content/dam/www/public/us/en/documents/datasheets/300-series-chipset-pch-datasheet-vol-1.pdf
https://www.intel.com/content/dam/www/public/us/en/documents/datasheets/300-series-chipset-pch-datasheet-vol-2.pdf
Otherwise, I am not really sure if this patch is correct, or if it is just working around an oddity in your specific BIOS that other people may not be experiencing.

**Comment by mithrandir42** [comment]
Answering without having fully viewed the spec, yet. As I also have written in the first pull request, it is possible, that the BIOS does this weird reordering. Since I do not have access to more machines with nvme drives, I cannot try this out. In my opinion it is at least inconvenient if the order in rst mode differs from the order in ahci mode. Well, there there are no guarantees on the device nodes order. But I think on one machine these should be as stable as possible. Grub for example cannot use uuids for the root drive when nor using initrd. This means a machine without initrd might get unbootable when switching between rst and ahci. So basically, if we cannot find a reason for the reordering in the remapping code or in the spec, we have to find out if this is an issue for all (or the majority of) devices or just mine. Do you have access to one or more devices with multiple nvme disks and the option to switch between rst and ahci mode in BIOS?

Anyways, I will have a further look at the spec and the affected kernel code and see if I can find the reason.

**Comment by dsd** [comment]
I don't quite follow your points around grub  - how is a kernel patch going to help any limitations in grub? And grub is capable of searching for partitions by UUID, partition type, label, etc, and can even be restricted to search only on the disk that the BIOS booted from. That's how we solve this class of problem in Endless OS meaning that the boot process is completely unaffected by any change in device node numbering or naming.

**Pull request closed without merging**
