### PR TITLE
intel_idle: Disable all C6 states for Asus Z550MA

### PR DESCRIPTION
**Pull request by carlocaione**
https://phabricator.endlessm.com/T6380

### CODE REVIEW

**Comment by parrotgeek1** [comment]
Doesn't this bug affect N2807 too - which the Endless One uses?!

A better patch is here

https://build.opensuse.org/package/view_file?file=22160-Intel-C6-EOI.patch&package=xen&project=home%3Acharlesa%3AopenSUSE11.3&rev=7

Except you will need to adjust CPUID checks for N2807 etc instead of Core i7

also the command line argument tsc.reliable=1 helps with freezes on Atom & Celeron Bay Trail

**Comment by carlocaione** [comment]
@parrotgeek1 we have never seen this issue on the N2807 but the patch seems promising. Can you open a ticket on phabricator so we can track this down?

**Comment by parrotgeek1** [comment]
apparently, it was band-aid fixed by Intel in newer BIOS, which the One probably has 

http://www.intel.com/content/dam/www/public/us/en/documents/specification-updates/pentium-n3520-j2850-celeron-n2920-n2820-n2815-n2806-j1850-j1750-spec-update.pdf

VLP52.

EOI Transactions May Not be Sent if Software Enters Core C6 During an Interrupt Service Routine
If core C6 is entered after the start of an interrupt service routine but before a write to the APIC EOI (End of Interrupt) register, and the core is woken up by an event other than a fixed interrupt source the core may drop the EOI transaction the next time APIC EOI register is written and further interrupts from the same or lower priority level will be blocked.
EOI transactions may be lost and interrupts may be blocked when core C6 is used during interrupt service routines.

-----> It is possible for the firmware to contain a workaround for this erratum. For the steppings affected, see “Summary Table of Changes”.

**Comment by parrotgeek1** [comment]
I can't use phabricator, it won't let me register with a gmail

**Comment by carlocaione** [comment]
@parrotgeek1 well, apparently I confused you with another guy also called Ethan who works in Endless, sorry for that :)
IIRC we actually already tried that fix on the Asus Z550MA and it didn't work, but I'll upgrade the internal ticket with a pointer to this patch, just in case we see other computers in the wild affected by the same issue.
Thank you for the time you spent on this, really appreciated.

**Comment by parrotgeek1** [comment]
bay trail cpuid is 0x37

here is a list of the other affected cpus to add 
https://www.google.com/search?q=apic+eoi+c6+site%3Aintel.com&oq=apic+eoi+c6+site%3Aintel.com&aqs=chrome..69i57.6559j0j1&sourceid=chrome&ie=UTF-8#q=%22May+Not+be+Sent+if+Software+Enters+Core+C6%22+site:intel.com&start=0&filter=0

**Pull request closed without merging**
