### PR TITLE
Fix order of remapped nvme devices.

### PR DESCRIPTION
**Pull request by mithrandir42**
Not using this kernel, but since the origin of the nvme remapping is here, I want to give back the fix for the nvme drive order problem I have encountered. Works fine for me with zen-sources: https://github.com/zen-kernel/zen-kernel/pull/227

At least with my hardware the nvme devices are being ordered the opposite way in rst mode than in ahci mode. I.e., with three drives, nvme0n1(in ahci mode) becomes nvme2n1 in rst mode. For non initrd users this means grub cannot find the root partition when switching between ahci and rst in bios. Assuming this is a general issue and not just with my hardware (Dell Precision 7550). If there are complaints from other users (with other devices) about the ordering being wrong for them, this should be easy to revert.

### CODE REVIEW

**Comment by jprvita** [comment]
test this please

(for the CI bot)

**Comment by jprvita** [comment]
Thanks for your bug report and contribution!

While the changes here are very simple, I don't have access the NVMe drives myself, or am super familiar with this kind of hardware, to be confident that changing the order won't have other negative side-effects. @dsd, who is the author of this code, is currently on vacation, so this will need to wait for him to be back in about 2 weeks before it gets properly reviewed and merged.

In the meantime, could you please adjust the commit message and break the lines on or before column 72?

**Comment by mithrandir42** [comment]
Well, I don`t get it. What do you want me to adjust the commit message to? Which line break do you mean? I don`t see a column 72 in the line of the PR.

**Comment by mithrandir42** [comment]
Changing the commit message somehow broke the history and closed the PR. Created a new one: https://github.com/endlessm/linux/pull/590

**Pull request closed without merging**
